[tool.ruff.lint]
select = ["ALL"]

[tool.ruff]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D107", "FBT001", "FBT002", "N802", "N803", "N806", "T201", "TRY003", "PD008", "PD009", "ANN101", "ANN204", "FA100", "FA102", "PERF203"]
line-length = 200
select = ["PLR0913"]

[tool.ruff.pylint]
max-args = 10

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true

[tool.mypy]
strict = false

[[tool.mypy.overrides]]
module = ["pyomo.*", "cloudpickle.*", "streamlit.*", "torch.*"]
ignore_missing_imports = true
ignore_errors = true